// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtdrmhrmcmjcrkqtzbxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0ZHJtaHJtY21qY3JrcXR6YnhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4ODg4MTYsImV4cCI6MjA2NDQ2NDgxNn0.bAEV-c7ogwk_PVd4zHwuNn9sXl7XxS78X36ynj_ESTY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});